name: Test

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Install composer
        uses: php-actions/composer@v6
      -
        name: "PHPStan"
        shell: 'script -q -e -c "bash {0}"'
        run: ./vendor/bin/phpstan analyse -c Resources/Private/Configuration/phpstan.neon
      -
        name: "PHP CS Fixer"
        shell: 'script -q -e -c "bash {0}"'
        run: ./vendor/bin/php-cs-fixer fix --config=vendor/typo3/coding-standards/templates/extension_php-cs-fixer.dist.php --dry-run --stop-on-violation --using-cache=no Classes
